language: scala
jdk:
  - oraclejdk8
before_install: unset SBT_OPTS JVM_OPTS
script:
  - make softlint
  - make test
  - './activator "set unmanagedSourceDirectories in Compile := Seq(file(\".\"))" coverageReport'
after_success: './activator "set unmanagedSourceDirectories in Compile := Seq(file(\".\"))" coveralls'
